-- KindRide rides schema (minimal for Session 12+)
-- Purpose:
-- 1) Store one ride per trip session (id = rideId generated by the app).
-- 2) Allow backend to validate that the ride is actually "completed"
--    before awarding points.
--
-- Run in Supabase SQL Editor. It is safe to re-run (uses IF NOT EXISTS).

-- Table
create table if not exists public.rides (
  id uuid primary key,
  driver_id uuid not null references auth.users(id) on delete cascade,
  passenger_id uuid null references auth.users(id) on delete set null,

  status text not null default 'completed'
    check (status in ('requested', 'in_progress', 'completed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz null
);

-- Enable row-level security
alter table public.rides enable row level security;

-- Users can read only their own rides
drop policy if exists "rides_select_driver_or_passenger" on public.rides;
create policy "rides_select_driver_or_passenger"
on public.rides
for select
to authenticated
using (auth.uid() = driver_id or auth.uid() = passenger_id);

-- Prevent clients from directly inserting/updating rides.
revoke insert, update, delete on public.rides from anon, authenticated;

